language: python
python:
- 2.7
- 3.5
script: pytest
env:
- PYTHONPATH=.
deploy:
  provider: pypi
  user: davidcarboni
  on:
    tags: true
    branch: master
  password:
    secure: aAp2PtC2Gyjhp21FLg/+RoVQPMStJZqqJYMBTom+evAmznSadPAdfPlp7TvoXqvPX7nwFJS9iOFcL7n681eW0Uhk15Cppw5nOh8wJIQSPFgsZLaBBnkRa/cHwQMFQ+7oGG2jPCTL7U6sHKDMo8ctfc5JiDxHHqnqNb3e3K117RjoNxhfUYfugAZJpqOhHpRwwJJXEe7WV8JluhpfNGYE8EX6pH/6848btaI7PabPZhQ9fCoTmeQtWYmcBaQMgd08C0P1UTmi9KTgHwt0BzVqfQ7NBqps+Z0ExcoZG1Sn0NDAbrjgF4Q6ivjEEVDuTge4yFc8LynFGC0aRfvH/qL6WNqjVQ+S8m6R/lrO7Af5tC7IoDGFDSImteNWVyrx68kyDkwy8/X/BuwlSQlvv2/p3KEmeQGbJs2SAvkkIkWQ7YR7Bbgji8r4TpSlpHwTxTqwhX9M6qP5BdNDU/RecvU6sfKwvLpa/WM3aVY6Cki+AgvTFYqwJYvIJQgfeAuzIDu9dCIsWPdJuZDCa4Ocg8OznTgXKUvQLEjqnWglyUpu+fSCTR5ZZPvDUjTWnUWTnD8uvqKA++i4jbsjqSkG3xYZDf6XD8V1IJ6ReKjNiL1N48Z4cqkxMs6n+MJe85gKWL7Q6WIAv9v82kZQlqM/8MfTgMCOOVjuB5H9eJHnivJJcBk=
