language: python
python:
- 2.7
- 3.5
script: pytest
env:
- PYTHONPATH=.
deploy:
  provider: pypi
  user: davidcarboni
  password:
    secure: vzGmFObisCVq6a65stpCN2PjKzHi2NdtNiEO79DACRpbQcLWA2g7x+EiGd1eC9/0/ilzfqWnUqDJuNhAFjkMREKYD+I+aqCq7WUI9UOTsuyelDwMwmLtAtrNJIcWl9i2bgTSyFmL4YLGC3Q1B69NXk1WgK/Y+IPP+X+QvxGlQ/yqnaMTmK2guIV03P+TCBeHMgu5Eqi6IxzbO03FyYB/4qBKInp35oHPoHMzrmoqhv5S089iXY1eHqqRRWUaAs1XPU41esfkLYFSq2/GfPijwMcrr87RrXTTQFpOJK8uov/zX65PwWm3tNgARyrAbYWi0XmsJIWYbJueZrTY81WQ+0EAR5rVEUhYNKFt4MpbPobj8MNeb/7KsWhaS3kopx1fQP9RZRQFjMkAg+yQo5ywVUJPEKeTRtOAIqISQcH1F80uUDubKzhmMSI0ceKzi9szEpFkgKgIRFvGQ4C991XoMIC99UOw1QNaNNnxk6obw+7MJW+PreJFKlP0Fymn4I3jK2xvndX3z1CK5aJa7e1rNiAEzBZALefn8Ul2a9s+b9DIbbDxI2TYTg04zlxkEhFNeRT8DSxOgr5+4AJluQs4192WgTKPzrTEQkCsnSO0iZiClG9NL8So07SFLWcSQfKJiO++de6Bz4wl4K1qGXMFveZMzRNRJNVHzgVhKgAJx6Y=
